### ISSUE TITLE
Join rosetta-rs?

### ISSUE THREAD

**Issue by epage** [rosetta-rs/template-benchmarks-rs#79]
I've been maintaining several benchmark repos based off of `template-benchmarks-rs`.  I've noticed there are [several other benchmark repos](https://www.reddit.com/r/rust/comments/w24rmg/github_epageparsebenchmarksrs/ignzypd/) that are hard to know about.

I've created rosetta-rs org as a place for these repos if the authors so choose to
- Increase discoverability
- Improve bus factor

See the [meta repo](https://github.com/rosetta-rs/team) for more details

Interested in collaborating?

**Comment by djc** [comment]
template-benchmarks-rs is really low on my priority list but I'm also not that interested in relinquishing any control.

How do you envision transferring this repo to rosetta-rs would change maintenance/bus factor?

**Comment by epage** [comment]
> How do you envision transferring this repo to rosetta-rs would change maintenance/bus factor?

You would maintain control.  If for some reason you become non-responsive online, org owners could then step in.  Org owners directly interfering with a repo would not be acceptable.  I have listed in the meta repo suggestions for what to cover but that is more to give people ideas and not to be prescriptive.

**Comment by djc** [comment]
Okay, let's do it. Can you give me permissions to create public repos in rosetta-rs?

**Comment by epage** [comment]
I've invited you though I think your can transfer the repo without it (though I don't know if you'll get the right permissions)
